#!/usr/bin/env bash
#Bash script that will display information about subdomains

data () {
        info=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
        echo "$2 $info" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 2 ]; then
        data "$1" "$2"
else
        subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
                data "$1" "$sub"
        done
fi
