#!/usr/bin/env bash
#installs and configure nginx to listen on port 80
# print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
