#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page 

redirect_301="\\\trewrite ^/redirect_me https://medium.com/@abenapomaa permanent;"
error_404="error_page 404 /404.html;"

apt-get update

apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
sed -i "30i $redirect_301" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "48i $error_404" /etc/nginx/sites-available/default

service nginx restart
