#!/usr/bin/env bash
# Loops "To infinity and beyond" with sleep 2 per each iteration
#   Displays "I am invincible!!!" at a sigterm signal

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
