#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format(fizzbuzz)

for fb in {1..100}
do
  if (( fb % 3 == 0 && fb % 5 == 0 ))
    then
        echo "FizzBuzz"
  elif (( fb % 3 == 0 ))
    then
        echo "Fizz"
  elif (( fb % 5 == 0 ))
    then
        echo "Buzz"
  else
      printf "%d\n" $fb;
  fi
  done
