#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd

while IFS=':' read -r login _ uid _ _ home _
do
    printf '%s:%s:%s\n' "${login}" "${uid}" "${home}"
done </etc/passwd
