#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and displays:
#   "bad luck" for the 4th iteration (China)
#   "good luck" for the 8th iteration
#   "Best School" for all other iterations

luck=0

while [ $luck -lt 10 ]
do
  if [ $luck -eq 3 ]
  then
    echo "bad luck"
  elif [ $luck -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( luck++ ))
done
