#!/usr/bin/env bash
#modify task1 fix to be short and sweet
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
